run_name: nwm_cdit_l

vggt:
  use_kv_cache: true
  checkpoint: /home/lih2511/GDiT/InfiniteVGGT/ckpt/checkpoints.pth
  img_size: 518
  patch_size: 14
  kv_cache_dim: 1024
  kv_cross_attn_start_layer: 16
  keep_ratio: 0.5
  prune_method: attention

# training setup
results_dir: logs
train: True
batch_size: 16
num_workers: 12
model: CDiT-B/2
lr: 8e-5
learn_sigma: true
allow_sigma_mismatch: false
from_checkpoint: config/cdit_b/checkpoints/0100000.pth.tar

# normalization for the action space
normalize: True
grad_clip_val: 10.0
context_size: 4

# distance bounds for distance and action and distance predictions 
distance:
  min_dist_cat: -64
  max_dist_cat: 64

# action output params
len_traj_pred: 64

# dataset specific parameters
image_size: 224
datasets:
  recon:
    data_folder: /data11/yangyf2505/nwm/data/recon
    train: data_splits/recon/train/ # path to train folder with traj_names.txt
    test: data_splits/recon/test/ # path to test folder with traj_names.txt
    goals_per_obs: 4
  tartan_drive:
    data_folder: /data/data/yangyf2505/nwm/data/tartandrive
    train: data_splits/tartan_drive/train/
    test: data_splits/tartan_drive/test/
    goals_per_obs: 4
  sacson:
    data_folder: /data11/yangyf2505/nwm/data/sacson
    train: data_splits/sacson/train
    test: data_splits/sacson/test
    goals_per_obs: 4
  scand:
    data_folder: /data11/yangyf2505/nwm/data/scand
    train: data_splits/scand/train
    test: data_splits/scand/test
    goals_per_obs: 4