run_name: nwm_cdit_l

vggt:
  use_kv_cache: true
  checkpoint: /home/JJ_Group/lih2511/GDiT/InfiniteVGGT/ckpt/checkpoints.pth
  img_size: 518
  patch_size: 14
  kv_cache_dim: 1024
  kv_cross_attn_start_layer: 16
  keep_ratio: 0.5
  prune_method: attention

# training setup
results_dir: logs
train: True
batch_size: 1
num_workers: 8
model: CDiT-L/2
lr: 8e-5

# normalization for the action space
normalize: True
grad_clip_val: 10.0
context_size: 4

# distance bounds for distance and action and distance predictions 
distance:
  min_dist_cat: -64
  max_dist_cat: 64

# action output params
len_traj_pred: 64

# dataset specific parameters
image_size: 224
datasets:
  recon:
    data_folder: /home/JJ_Group/lih2511/GDiT/nwm/data/recon/train/  # 指向实际数据文件
    train: /home/JJ_Group/lih2511/GDiT/nwm/data_splits/recon/train/  # 指向traj_names.txt文件
    test: /home/JJ_Group/lih2511/GDiT/nwm/data_splits/recon/test/  # 指向测试traj_names.txt文件
    goals_per_obs: 4